# aliases.conf — nombre_archivo=Nombre Amigable
1384479.png=Abstract
auditory.png=Auditory
deep-dive-into-coding-realms-ky-3440x1440.jpg=Deep Dive
ghost.jpg=Ghost
lofi-boy-in-deep-thoughts-46.jpg=Lofi Boy
ninja.jpg=Ninja
ola.jpg=Ola
open-sourcerer-minimal-y6-3440x1440.jpg=Open Sourcerer
security-break-grim-reaper-ea-3440x1440.jpg=Grim Reaper
security-break-grim-reaper-hacker-qj-3440x1440.jpg=Grim Reaper Hacker
the-ghost-coders-rj-3440x1440.jpg=Ghost Coders
the-sinister-jj-3440x1440.jpg=Sinister
kali-blue-sticker.png=Kali Blue
