# aliases.conf — nombre_archivo=Nombre Amigable
GHOST-CODERS=Ghost Coders
WALLHAVEN1=Wallhaven 1
WALLHAVEN2=Wallhaven 2
WALLHAVEN3=Wallhaven 3
WALLHAVEN4=Wallhaven 4
WALLHAVEN5=Wallhaven 5
WALLHAVEN6=Wallhaven 6
WALLHAVEN7=Wallhaven 7
FIRE-SKULL=Fire Skull
PASTEL-CITY=Pastel City
VARIOUS-ARCH=Various Arch
