"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1500

format = """
[┌─](bold color_blue)[](fg:color_bg1)\
$os\
$username\
 $hostname\
[ ](fg:color_bg1 bg:color_bg2)\
$directory\
[ ](fg:color_bg2 bg:color_bg3)\
$git_branch\
$git_status\
[ ](fg:color_bg3 bg:color_bg4)\
$c\
$dotnet\
$java\
$kotlin\
$nodejs\
[ ](fg:color_bg4 bg:color_bg5)\
$cmd_duration\
[ ](fg:color_bg5)\
\n[└─](bold color_blue)$character\
"""

palette = "kali"

[palettes.kali]
#color_bg1 = "#1a1a1a"
#color_bg2 = "#111111"
#color_bg3 = "#0a0a0a"
#color_bg4 = "#050505"
#color_bg5 = "#000000"

color_blue = "#ff2d78"
color_gray = "#00802a"
color_red = "#ff2d78"
color_white = "#ffffff"

[character]
error_symbol = "[\\$](bold color_red) "
success_symbol = "[\\$](bold color_blue) "

[cmd_duration]
format = "[$duration](bg:color_bg5 fg:color_gray)"
min_time = 500

[directory]
style = "bg:color_bg2 fg:color_white"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color_bg3 fg:color_blue"
format = "[$symbol $branch]($style)"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[( $all_status$ahead_behind)]($style)'
style = "bold bg:color_bg3 fg:color_red"

[hostname]
format = "[@$hostname]($style)"
ssh_only = false
ssh_symbol = " "
style = "bg:color_bg1 fg:color_white"

[os]
format = "[$symbol]($style)"
style = "bg:color_bg1 fg:color_white"
disabled = false

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bg:color_bg1 fg:color_red"
style_user = "bg:color_bg1 fg:color_white"

[c]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#6295CB"
symbol = " "

[dotnet]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#1180C3"
symbol = " "

[java]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#F7901E"
symbol = " "

[kotlin]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#C017E4"
symbol = " "

[nodejs]
style = "bg:color_bg4 fg:#5FA04E"
format = '[$symbol($version)]($style)'
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
