# HYPRLOCK COLORS - TOKYO NIGHT
$accent      = rgba(7dcfffff)
$accent_alt  = rgba(9ece6aff)
$fg          = rgba(c0caf5ff)
$fg_dim      = rgba(565f89ff)
$bg          = rgba(0d0e17cc)
$red         = rgba(f7768eff)
