# HYPRLAND COLORS - TOKYO NIGHT
general {
    col.active_border   = rgba(7aa2f7cc)
    col.inactive_border = rgba(292e4266)
}

decoration {
    shadow {
        color          = rgba(000000cc)
        color_inactive = rgba(00000066)
    }
}
