# HYPRLOCK COLORS - TOKYO NIGHT
$accent      = rgba(7aa2f7ff)
$accent_alt  = rgba(bb9af7ff)
$fg          = rgba(c0caf5ff)
$fg_dim      = rgba(565f89ff)
$bg          = rgba(1a1b26cc)
$red         = rgba(f7768eff)
