# TOKYO NIGHT NEON
background            #0d0e17
foreground            #c0caf5
cursor                #00d4ff
selection_background  #1e2050
selection_foreground  #c0caf5

# Colores normales
color0  #111219
color1  #ff3d73
color2  #9bff68
color3  #ffd060
color4  #5597ff
color5  #cc66ff
color6  #00d4ff
color7  #a9b1d6

# Colores brillantes
color8   #3d4268
color9   #ff3d73
color10  #9bff68
color11  #ffd060
color12  #5597ff
color13  #cc66ff
color14  #00d4ff
color15  #c0caf5
