# TOKYO NIGHT
background            #0d0e17
foreground            #c0caf5
cursor                #c0caf5
selection_background  #7dcfff
selection_foreground  #0d0e17

# Colores normales
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7dcfff
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

# Colores brillantes
color8   #414868
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7dcfff
color13  #bb9af7
color14  #7dcfff
color15  #c0caf5
