# HYPRLAND COLORS - THORN FOREST
general {
    col.active_border   = rgba(87CBB1ff) rgba(6FA791ff) 45deg
    col.inactive_border = rgba(172526aa)
}

decoration {
    shadow {
        color         = rgba(131F20ee)
        color_inactive = rgba(131F20aa)
    }
}
