# HYPRLAND COLORS - ONE DARK
general {
    col.active_border   = rgba(61afefff)
    col.inactive_border = rgba(3e445188)
}

decoration {
    shadow {
        color         = rgba(1e2127ee)
        color_inactive = rgba(1e2127aa)
    }
}
