# HYPRLOCK COLORS - THORN FOREST
$accent      = rgba(87CBB1ff)
$accent_alt  = rgba(6FA791ff)
$fg          = rgba(DBD2C7ff)
$fg_dim      = rgba(9B9A8Cff)
$bg          = rgba(172526cc)
$red         = rgba(D2696Cff)
