# HYPRLAND COLORS - AUDITORY (Matrix)
general {
    col.active_border   = rgba(00ff41cc)
    col.inactive_border = rgba(008f1166)
}

decoration {
    shadow {
        color          = rgba(000000cc)
        color_inactive = rgba(00000066)
    }
}
