# TMUX TEMA: AUDITORY (KALI)
set -g status-style                "bg=#0a0a0f,fg=#e2eaf8"
set -g window-status-style         "bg=#0f0f1a,fg=#3a4060"
set -g window-status-current-style "bg=#ff2d78,fg=#000000,bold"
set -g pane-border-style           "fg=#0f0f1a"
set -g pane-active-border-style    "fg=#ff2d78"
set -g message-style               "bg=#ff2d78,fg=#000000,bold"
set -g mode-style                  "bg=#ff2d78,fg=#000000"
