# Thorn Forest — jpwol/thorn.nvim

[mgr]
cwd = { fg = "#9B9A8C", italic = true }

hovered         = { bg = "#26403E" }
preview_hovered = { bg = "#26403E" }

find_keyword  = { fg = "#172526", bg = "#FFD7AA", bold = true }
find_position = { fg = "#87CBB1", bg = "#1D3334", bold = true }

marker_copied   = { fg = "#6FA791", bg = "#6FA791" }
marker_cut      = { fg = "#D2696C", bg = "#D2696C" }
marker_marked   = { fg = "#F9ADA0", bg = "#F9ADA0" }
marker_selected = { fg = "#87CBB1", bg = "#87CBB1" }

count_copied   = { fg = "#172526", bg = "#6FA791" }
count_cut      = { fg = "#172526", bg = "#D2696C" }
count_selected = { fg = "#172526", bg = "#87CBB1" }

border_symbol = "│"
border_style  = { fg = "#87CBB1" }

[tabs]
active   = { fg = "#172526", bg = "#87CBB1" }
inactive = { fg = "#87CBB1", bg = "#1D3334" }

[mode]
normal_main = { fg = "#172526", bg = "#87CBB1", bold = true }
normal_alt  = { fg = "#87CBB1", bg = "#1D3334" }
select_main = { fg = "#172526", bg = "#9EC59B", bold = true }
select_alt  = { fg = "#9EC59B", bg = "#1D3334" }
unset_main  = { fg = "#172526", bg = "#6FA791", bold = true }
unset_alt   = { fg = "#6FA791", bg = "#1D3334" }

[status]
overall   = { fg = "#DBD2C7", bg = "#131F20" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#DBD2C7", bold = true }
progress_normal = { fg = "#568270", bg = "#26403E" }
progress_error  = { fg = "#D2696C", bg = "#26403E" }

perm_type  = { fg = "#91C4C0" }
perm_read  = { fg = "#FFD7AA" }
perm_write = { fg = "#D2696C" }
perm_exec  = { fg = "#6FA791" }
perm_sep   = { fg = "#568270" }

[pick]
border   = { fg = "#87CBB1" }
active   = { fg = "#DBD2C7", bg = "#26403E" }
inactive = { fg = "#DBD2C7" }

[input]
border   = { fg = "#87CBB1" }
title    = { fg = "#87CBB1" }
value    = { fg = "#9EC59B" }
selected = { bg = "#26403E" }

[cmp]
border   = { fg = "#87CBB1" }
active   = { fg = "#DBD2C7", bg = "#26403E" }
inactive = { fg = "#DBD2C7" }
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#87CBB1" }
title   = { fg = "#87CBB1" }
hovered = { fg = "#DBD2C7", bg = "#26403E" }

[which]
cols            = 3
mask            = { bg = "#131F20" }
cand            = { fg = "#87CBB1" }
rest            = { fg = "#91C4C0" }
desc            = { fg = "#9EC59B" }
separator       = " ➜ "
separator_style = { fg = "#568270" }

[confirm]
border     = { fg = "#87CBB1" }
title      = { fg = "#87CBB1" }
btn_yes    = { bg = "#26403E" }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = { fg = "#87CBB1" }
title  = { fg = "#87CBB1" }

[notify]
title_info  = { fg = "#87CBB1" }
title_warn  = { fg = "#FFD7AA" }
title_error = { fg = "#D2696C" }
icon_error  = ""
icon_warn   = ""
icon_info   = ""

[help]
on      = { fg = "#6FA791" }
run     = { fg = "#9EC59B" }
desc    = { fg = "#87CBB1" }
hovered = { bg = "#26403E" }
footer  = { fg = "#DBD2C7", bg = "#172526" }

[filetype]
rules = [
    { mime = "image/*",                                          fg = "#FFD7AA" },
    { mime = "{audio,video}/*",                                  fg = "#F9ADA0" },
    { mime = "application/*zip",                                 fg = "#D2696C" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}",  fg = "#D2696C" },
    { mime = "application/{pdf,doc,rtf,vnd.*}",                  fg = "#91C4C0" },
    { url = "*", is = "orphan", bg = "#D2696C" },
    { url = "*", is = "exec",   fg = "#6FA791" },
    { url = "*/",               fg = "#87CBB1" },
    { url = "*",                fg = "#DBD2C7" },
]
