#==========================
# MPV - DOTFILES ARCH
#==========================

#-----------
# VÍDEO
#-----------
# Usar GPU para renderizado (mejor rendimiento)
vo=gpu
gpu-api=vulkan
hwdec=auto-safe

# Calidad de escalado
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

#-----------
# AUDIO
#-----------
ao=pipewire
volume=80
volume-max=150

#-----------
# SUBTÍTULOS
#-----------
sub-auto=fuzzy
sub-font="GeistMono Nerd Font"
sub-font-size=42
sub-color="#ebdbb2"
sub-border-color="#1d2021"
sub-border-size=2
sub-shadow-color="#00000066"
sub-shadow-offset=1

#-----------
# INTERFAZ
#-----------
# Sin barra de título (funciona en Wayland con Hyprland)
title="${filename}"
border=no
osc=yes

# Mantener posición al reabrir
save-position-on-quit=yes

#-----------
# PANTALLA
#-----------
# Fullscreen al abrir vídeos grandes
# fullscreen=yes

# Ajustar ventana al tamaño del vídeo
autofit-larger=80%x80%

#-----------
# CACHÉ
#-----------
cache=yes
demuxer-max-bytes=150MiB
demuxer-readahead-secs=20

#-----------
# CAPTURAS DE PANTALLA
#-----------
screenshot-format=png
screenshot-directory="~/Imágenes/capturas-mpv"
screenshot-template="%F_%P"
