#==========================
# BTOP - DOTFILES ARCH
#==========================

# Tema alineado con gruvbox
color_theme = "gruvbox_dark_v2"

# Modo de visualización
vim_keys = True
rounded_corners = True
graph_symbol = "braille"

# Actualización cada 2 segundos
update_ms = 2000

# Mostrar en orden: CPU, MEM, NET, PROC
shown_boxes = "cpu mem net proc"

# CPU
cpu_graph_upper_color = "red"
cpu_graph_lower_color = "green"
cpu_invert_lower = True
cpu_single_graph = False

# Memoria
mem_graphs = True

# Procesos
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = True
proc_mem_bytes = True
