#==========================
# PACMAN.CONF - DOTFILES ARCH
#==========================

[options]
HoldPkg      = pacman glibc
Architecture = auto

# Colores en la salida de pacman
Color
# Animación de pacman al descargar
ILoveCandy
# Mostrar versiones al instalar/actualizar
VerbosePkgLists
# Descargas paralelas
ParallelDownloads = 5

CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

#==========================
# REPOSITORIOS
#==========================
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Multilib (apps 32 bits, Steam, Wine, etc.)
[multilib]
Include = /etc/pacman.d/mirrorlist
