# /etc/pacman.conf — configuración de pacman

[options]
HoldPkg     = pacman glibc
Architecture = auto

# Activar color en la salida
Color

# Barra de progreso divertida
ILoveCandy

# Mostrar lista de paquetes detallada antes de instalar
VerbosePkgLists

# Descargas paralelas (más rápido)
ParallelDownloads = 5

# Comprobar espacio disponible antes de instalar
CheckSpace

# Verificar firmas GPG (nunca desactivar)
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

#------
# REPOS
#------
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
