# HYPRLAND COLORS - KALI MODE
general {
    col.active_border   = rgba(ff2d78ff)
    col.inactive_border = rgba(0a0a0aaa)
}

decoration {
    shadow {
        color         = rgba(000000ee)
        color_inactive = rgba(000000aa)
    }
}
