# HYPRLAND COLORS - GRUVBOX
general {
    col.active_border   = rgba(d79921ff) rgba(fe8019ff) 45deg
    col.inactive_border = rgba(3c3836aa)
}

decoration {
    shadow {
        color         = rgba(1d2021ee)
        color_inactive = rgba(1d2021aa)
    }
}
