# HYPRLOCK COLORS - GRUVBOX
$accent      = rgba(d79921ff)
$accent_alt  = rgba(fe8019ff)
$fg          = rgba(ebdbb2ff)
$fg_dim      = rgba(a89984ff)
$bg          = rgba(1d2021cc)
$red         = rgba(cc241dff)
