# HYPRLOCK COLORS - TOKYO NIGHT STORM
$accent      = rgba(7dcfffff)
$accent_alt  = rgba(9ece6aff)
$fg          = rgba(c0caf5ff)
$fg_dim      = rgba(565f89ff)
$bg          = rgba(24283bcc)
$red         = rgba(f7768eff)
