# HYPRLOCK COLORS - KALI MODE
$accent      = rgba(00ff41ff)
$accent_alt  = rgba(ff2d78ff)
$fg          = rgba(e2eaf8ff)
$fg_dim      = rgba(00802aff)
$bg          = rgba(000000cc)
$red         = rgba(ff1744ff)
