# HYPRLAND COLORS - TOKYO NIGHT STORM
general {
    col.active_border   = rgba(7dcfffff) rgba(bb9af7ff) 45deg
    col.inactive_border = rgba(24283baa)
}

decoration {
    shadow {
        color         = rgba(1d202fee)
        color_inactive = rgba(1d202faa)
    }
}
