# HYPRLAND COLORS - TOKYO NIGHT
general {
    col.active_border   = rgba(7dcfffff) rgba(bb9af7ff) 45deg
    col.inactive_border = rgba(1a1b2eaa)
}

decoration {
    shadow {
        color         = rgba(0d0e17ee)
        color_inactive = rgba(0d0e17aa)
    }
}
