# HYPRLAND COLORS - TOKYO NIGHT NEON
general {
    col.active_border   = rgba(00d4ffff) rgba(cc66ffff) 45deg
    col.inactive_border = rgba(0d0e17aa)
}

decoration {
    shadow {
        color         = rgba(00d4ff33)
        color_inactive = rgba(0d0e17aa)
    }
}
