# TMUX TEMA: TOKYO NIGHT STORM
set -g status-style                "bg=#24283b,fg=#c0caf5"
set -g window-status-style         "bg=#1f2335,fg=#565f89"
set -g window-status-current-style "bg=#7dcfff,fg=#24283b,bold"
set -g pane-border-style           "fg=#1f2335"
set -g pane-active-border-style    "fg=#7dcfff"
set -g message-style               "bg=#7dcfff,fg=#24283b,bold"
set -g mode-style                  "bg=#7dcfff,fg=#24283b"
