# TMUX TEMA: TOKYO NIGHT
set -g status-style                "bg=#1a1b2e,fg=#c0caf5"
set -g window-status-style         "bg=#16213e,fg=#565f89"
set -g window-status-current-style "bg=#7dcfff,fg=#1a1b2e,bold"
set -g pane-border-style           "fg=#16213e"
set -g pane-active-border-style    "fg=#7dcfff"
set -g message-style               "bg=#7dcfff,fg=#1a1b2e,bold"
set -g mode-style                  "bg=#7dcfff,fg=#1a1b2e"
