#==========================
# HYPRIDLE - DOTFILES ARCH
#==========================

general {
    # Evita bloquear si hay audio reproduciéndose
    lock_cmd = pidof hyprlock || hyprlock
    # Enciende la pantalla al volver de suspensión
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 10 minutos inactivo → bloquear pantalla
listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
    on-resume  = hyprctl dispatch dpms on
}

# 30 minutos inactivo → apagar pantalla
listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}
