# HYPRLOCK COLORS - ONE DARK
$accent      = rgba(61afefff)
$accent_alt  = rgba(98c379ff)
$fg          = rgba(abb2bfff)
$fg_dim      = rgba(5c6370ff)
$bg          = rgba(1e2127cc)
$red         = rgba(e06c75ff)
