#===================
# REGLAS DE VENTANAS
#===================

#-----------
# FLOTANTES
#-----------
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(imv)$
windowrule = float, class:^(mpv)$
windowrule = float, title:^(Confirm)(.*)$
windowrule = float, title:^(Open File)(.*)$
windowrule = float, title:^(Save As)(.*)$

#--------------------
# TAMAÑO DE FLOTANTES
#--------------------
windowrule = size 800 600, class:^(pavucontrol)$
windowrule = size 900 600, class:^(blueman-manager)$

#---------
# CENTRADO
#---------
windowrule = center, class:^(pavucontrol)$
windowrule = center, class:^(blueman-manager)$
windowrule = center, class:^(nm-connection-editor)$

#------------------------
# BLUR EXTRA EN FLOTANTES
#------------------------
windowrule = opacity 0.92, class:^(rofi)$

#-----------------
# WORKSPACES FIJOS
#-----------------
windowrule = workspace 2, class:^(brave-browser)$
windowrule = workspace 2, class:^(firefox)$
windowrule = workspace 2, class:^(tor-browser)$
windowrule = workspace 3, class:^(nvim)$
windowrule = workspace 4, class:^(thunar)$
windowrule = workspace 6, class:^(thunderbird)$
windowrule = workspace 8, class:^(discord)$
windowrule = workspace 8, class:^(spotify)$

#---------
# XWAYLAND
#---------
# Fuerza escala 1 en apps XWayland para evitar blur
windowrule = xray 1, xwayland:1
