# HYPRLAND COLORS - DESKTOP (One Dark / TokyoNight)
general {
    col.active_border   = rgba(aaaaaacc)
    col.inactive_border = rgba(44444466)
}

decoration {
    shadow {
        color          = rgba(000000cc)
        color_inactive = rgba(00000066)
    }
}
