#==========================
# YAZI - DOTFILES ARCH
#==========================

[manager]
ratio          = [1, 4, 3]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[preview]
tab_size       = 2
max_width      = 600
max_height     = 900
cache_dir      = ""

[opener]
edit = [
    { run = 'nvim "$@"', desc = "Neovim", block = true },
]
open = [
    { run = 'xdg-open "$@"', desc = "Abrir con app por defecto" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$1")"', desc = "Mostrar en gestor de archivos" },
]

[plugin]
prepend_previewers = [
    { mime = "video/*", run = "video" },
]

[open]
rules = [
    { mime = "text/*",        use = "edit" },
    { mime = "image/*",       use = ["imv", "open"] },
    { mime = "video/*",       use = ["mpv", "open"] },
    { mime = "audio/*",       use = ["mpv", "open"] },
    { mime = "application/pdf", use = ["zathura", "open"] },
    { mime = "*",             use = ["open"] },
]
